# ---

# root: true


env:
  browser: true
  es2021: true
  node: true
  mocha: true

extends:
  - airbnb-base
  # - plugin:import/recommended
  # - plugin:import/errors
  - plugin:import/warnings

parserOptions:
  ecmaVersion: latest
  sourceType: module



rules:
  no-console: 0

  import/extensions: 0
  import/no-named-as-default: 0
