# ---

# root: true


env:
  browser: true
  es2021: true
  node: true

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules: {
   no-console: 0,
  #  "no-restricted-syntax": [
  #     "error",
  #     {
  #         "selector": "CallExpression[callee.object.name='console'][callee.property.name!=/^(log|warn|error|info|trace)$/]",
  #         "message": "Unexpected property on console object was called"
  #     }
  # ]

    import/extensions: 0
  # new-cap:
  #   - error
  #   - properties: false
  # no-param-reassign:
  #   - error
  #   - props: true
  #     ignorePropertyModificationsFor:
  #     - req
  #     - reply
  # no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]

}
